{
 "title": "Multi-Cluster Dashboard",
 "tags": [ "MNTN" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "v_schema",
    "label": "Cluster",
    "query": "SELECT name AS __text, public.cluster_metrics_schema(id) AS __value FROM public.clusters ORDER BY name;"
   },
   { "name": "v_interval", "label": "Interval Seconds", "query": "60,300,600,900,1800" }
  ]
 },
 "panels": [
  {
   "title": "Monitor Load Summary (past 24 hrs)",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT lf.funcname AS \"Load Function\"\n     , CASE WHEN ls.summary = 'success' THEN 'Success' ELSE 'FAILURE' END AS \"Outcome\"\n     , count(*) AS \"Counts\"\n  FROM public.load_functions lf\n       LEFT JOIN public.load_status ls ON (lf.id = ls.load_function_id)\n WHERE ls.txstart > now() - interval'24 hours'\n   AND cluster_id = public.cluster_id_from_schema('$v_schema')\n GROUP BY 1, 2\n ORDER BY 2, 1;\n"
    }
   ]
  },
  {
   "title": "Monitor Load Detail (past 24 hrs)",
   "type": "table",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT ls.txstart AS \"Iteration\"\n     , CASE WHEN ls.summary = 'success' THEN 'Success' ELSE 'FAILURE' END AS \"Outcome\"\n     , (max(ls.created) - min(ls.created)) AS \"Run Time\"\n     , count(*) AS \"Count\"\n     , array_agg(lf.funcname) AS \"Functions\"\n  FROM public.load_status ls\n       JOIN public.load_functions lf ON (ls.load_function_id = lf.id)\n WHERE ls.txstart > now() - interval'24 hours'\n    AND ls.cluster_id = public.cluster_id_from_schema('$v_schema')\n GROUP BY 1, 2\n ORDER BY 1 DESC, 2;\n"
    }
   ]
  },
  {
   "title": "Database State",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT 'Database uptime' AS name, uptime::text AS value FROM ${v_schema}.dbuptime\nUNION\nSELECT 'Database version' AS name, split_part(version,')',1)||')' AS value FROM ${v_schema}.version\nUNION\nSELECT 'Connections' AS name, count(*)::text AS value FROM ${v_schema}.cat_pg_stat_activity\nORDER BY name ASC;\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Database Health",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH confpri AS (\nSELECT count(*) FROM ${v_schema}.cat_gp_segment_configuration WHERE role='p'\n), confmir AS (\nSELECT count(*) FROM ${v_schema}.cat_gp_segment_configuration WHERE role='m'\n), confrole AS (\nSELECT count(*) FROM ${v_schema}.cat_gp_segment_configuration WHERE preferred_role=role\n), confsync AS (\nSELECT count(*) FROM ${v_schema}.cat_gp_segment_configuration WHERE status = 'd'\n)\nSELECT '1. Primary Segments' AS name, count::text AS value FROM confpri\nUNION\nSELECT '2. Mirror Segments' AS name, count::text AS value FROM confmir\nUNION\nSELECT '3. Down Segements' AS name, count::text AS value from confsync\nUNION\nSELECT '4. Cluster Health' AS name\n     , CASE WHEN (cp.count + cm.count = cr.count AND cs.count = 0) THEN 'Healthy'\n            ELSE 'DEGRADED' END AS value\n  FROM confrole cr, confpri cp, confmir cm, confsync cs\nORDER BY 1 ASC \n"
    }
   ]
  },
  {
   "title": "Coordinator Storage Consumption",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH maxes AS (\nSELECT max(period) FROM ${v_schema}.disk_space\n), src AS ( \nSELECT DISTINCT d.*\n  FROM ${v_schema}.disk_space d, maxes m, public.cluster_hosts h\n WHERE m.max = d.period\n   AND h.hostname = d.hostname\n   AND h.is_mdw\n)\nSELECT period as time, sum(used_kbs) AS \"Used KBs\", sum(avail_kbs) AS \"Avail KBs\"\n  FROM src\n GROUP BY 1;\n"
    }
   ]
  },
  {
   "title": "Segment Storage Consumption",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH maxes AS (\nSELECT max(period) FROM ${v_schema}.disk_space\n), src AS ( \nSELECT DISTINCT d.*\n  FROM ${v_schema}.disk_space d, maxes m, public.cluster_hosts h\n WHERE m.max = d.period\n   AND h.hostname = d.hostname\n   AND NOT h.is_mdw\n)\nSELECT period as time, sum(used_kbs) AS \"Used KBs\", sum(avail_kbs) AS \"Avail KBs\"\n  FROM src\n GROUP BY 1;\n"
    }
   ]
  },
  {
   "title": "Segment Swap Usage",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH maxes AS (\nSELECT max(period) FROM ${v_schema}.swap\n), src AS (\nSELECT DISTINCT d.*\n  FROM ${v_schema}.swap d, maxes m, public.cluster_hosts h\n WHERE m.max = d.period\n   AND h.hostname = d.hostname\n)\nSELECT period as time, sum(swpused_pct) AS \"Used %\", 100 - sum(swpused_pct) AS \"Avail %\"\n  FROM src\n GROUP BY 1;\n"
    }
   ]
  },
  {
   "title": "Segment Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 21 },
   "targets": [
    {
     "rawSql": "WITH maxes AS (\nSELECT max(period) FROM ${v_schema}.memory\n), src AS (\n-- many segments may exist on same mntpt\nSELECT DISTINCT d.*\n  FROM ${v_schema}.memory d, maxes m, public.cluster_hosts h\n WHERE m.max = d.period\n   AND h.hostname = d.hostname\n)\nSELECT period as time, sum(memused_pct) AS \"Used %\", 100 - sum(memused_pct) AS \"Avail %\"\n  FROM src\n GROUP BY 1;\n"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select now() as time, max_conn, used, res_for_super, (max_conn - used - res_for_super) AS res_for_normal\n  from (select count(*) used from ${v_schema}.cat_pg_stat_activity) t1,\n  (select setting::int res_for_super from ${v_schema}.cat_pg_settings where name='superuser_reserved_connections') t2,\n  (select setting::int max_conn from ${v_schema}.cat_pg_settings where name='max_connections') t3; "
    }
   ]
  },
  {
   "title": "Cluster Load",
   "type": "table",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH period AS (\nSELECT min(max) AS max\n  FROM (SELECT hostname, max(ts_round(period,60))\n          FROM ${v_schema}.ldavg GROUP BY hostname) n\n), cores AS (\nSELECT value::int\n  FROM public.cluster_attribs\n WHERE domain = 'segment.host.cores'\n), ldavgs AS (\nSELECT ts_round(l.period,60) AS time\n     , (sum(l.ldavg_1) / c.value)::numeric(10,2) AS ldavg_1\n     , (sum(l.ldavg_5) / c.value)::numeric(10,2) AS ldavg_5\n     , (sum(l.ldavg_15) / c.value)::numeric(10,2) AS ldavg_15\n  FROM ${v_schema}.ldavg l, period p, cores c\n WHERE ts_round(period,60) = p.max\n GROUP BY 1, c.value\n), total_cores AS (\nSELECT c1.value::int * c2.value::int AS value\n  FROM public.cluster_attribs c1, public.cluster_attribs c2\n WHERE c1.domain = 'segment.hosts'\n   AND public.cluster_id_from_schema('${v_schema}') = c1.cluster_id\n   AND c2.domain = 'segment.host.cores'\n   AND public.cluster_id_from_schema('${v_schema}') = c2.cluster_id\n)\nSELECT l.time\n     -- , ca.value::int AS cores\n     , (CASE WHEN ldavg_1 < (ca.value::int * 0.25) THEN 'Low Load'\n             WHEN ldavg_1 < (ca.value::int * 0.60) THEN 'Medium Load'\n             ELSE 'High Load' END)||' ('|| ldavg_1 ||')' AS \"1 Minute Load\"\n     , (CASE WHEN ldavg_5 < (ca.value::int * 0.25) THEN 'Low Load'\n             WHEN ldavg_5 < (ca.value::int * 0.60) THEN 'Medium Load'\n             ELSE 'High Load' END)||' ('|| ldavg_5 ||')' AS \"5 Minute Load\"\n     , (CASE WHEN ldavg_15 < (ca.value::int * 0.25) THEN 'Low Load'\n             WHEN ldavg_15 < (ca.value::int * 0.60) THEN 'Medium Load'\n             ELSE 'High Load' END)||' ('|| ldavg_15 ||')' AS \"15 Minute Load\"\n  FROM ldavgs l, total_cores ca;"
    }
   ]
  },
  {
   "title": "Cluster Load",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH period AS (\nSELECT min(max) AS max\n  FROM (SELECT hostname, max(ts_round(period,60))\n          FROM ${v_schema}.ldavg GROUP BY hostname) n\n), cores AS (\nSELECT value::int\n  FROM public.cluster_attribs\n WHERE domain = 'segment.host.cores'\n   AND public.cluster_id_from_schema('${v_schema}') = cluster_id\n)\nSELECT ts_round(l.period,60) AS time\n     , (sum(l.ldavg_1) / c.value)::numeric(10,2) AS \"1 Minute % Load\"\n     , (sum(l.ldavg_5) / c.value)::numeric(10,2) AS \"5 Minute % Load\"\n     , (sum(l.ldavg_15) / c.value)::numeric(10,2) AS \"15 Minute % Load\"\n  FROM ${v_schema}.ldavg l, period p, cores c\n WHERE ts_round(period,60) = p.max\n GROUP BY 1, c.value;"
    }
   ]
  },
  {
   "title": "User Connections",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select usename,application_name,state,count(*)\n  from ${v_schema}.cat_gp_stat_activity\n where usename is not null\n   and gp_segment_id = -1\n group by 1, 2, 3\n order by 1, 2, 3;"
    }
   ]
  },
  {
   "title": "System Activity Summary",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select backend_type,state,count(*)\n  from ${v_schema}.cat_pg_stat_activity\n group by 1, 2\n order by 1"
    }
   ]
  },
  {
   "title": "Current Load Average 1 Minute",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "WITH m AS (\nSELECT min(max) AS max\n  FROM (SELECT hostname, max(ts_round(period,60))\n          FROM ${v_schema}.ldavg\n         GROUP BY hostname) n\n)\nSELECT ts_round(period,60) AS time, l.hostname, l.ldavg_1\n  FROM ${v_schema}.ldavg l, m\n WHERE ts_round(period,60) = m.max\n ORDER BY hostname;\n"
    }
   ]
  },
  {
   "title": "Current Load Average 5 Minute",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 43 },
   "targets": [
    {
     "rawSql": "WITH m AS (\nSELECT min(max) AS max\n  FROM (SELECT hostname, max(ts_round(period,60))\n          FROM ${v_schema}.ldavg\n         GROUP BY hostname) n\n)\nSELECT ts_round(period,60) AS time, l.hostname, l.ldavg_5\n  FROM ${v_schema}.ldavg l, m \n WHERE ts_round(period,60) = m.max\n ORDER BY hostname;\n"
    }
   ]
  },
  {
   "title": "Segment Storage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "WITH maxes AS (\nSELECT max(period) FROM ${v_schema}.disk_space\n), src AS ( \nSELECT DISTINCT d.*\n  FROM ${v_schema}.disk_space d, maxes m, public.cluster_hosts h\n WHERE m.max = d.period\n   AND h.hostname = d.hostname\n)\nSELECT period as time\n     , hostname\n     , sum(used_kbs) AS \"Used KBs\"\n     , sum(avail_kbs) AS \"Avail KBs\"\n  FROM src\nGROUP BY 1,2\nORDER BY 2\n \n"
    }
   ]
  },
  {
   "title": "Cluster Segment Configuration",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT hostname AS \"Hostname\"\n     , port AS \"Port\"\n     , datadir AS \"Segment Dir\"\n     , dbid AS \"Database ID\"\n     , content AS \"Content\"\n     , role AS \"Role\"\n     , preferred_role AS \"Preferred Role\"\n     , status AS \"Status\"\n     , mode AS \"Mode\"\n  FROM ${v_schema}.cat_gp_segment_configuration\n ORDER BY status ASC, hostname, port;"
    }
   ]
  },
  {
   "title": "Cluster Configuration History",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 67 },
   "targets": [
    {
     "rawSql": "SELECT h.time AS \"Time\"\n     , h.dbid AS \"Database ID\" \n     , s.hostname AS \"Hostname\"\n     , s.datadir AS \"Segment Dir\"\n     , h.\"desc\" AS \"Description\"\n  FROM ${v_schema}.cat_gp_configuration_history h JOIN ${v_schema}.cat_gp_segment_configuration s USING (dbid)\n ORDER BY 1 DESC;"
    }
   ]
  },
  {
   "title": "Cumulative Cluster Disk Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    ts_round(d.period, $v_interval ) AS time\n  , sum(used_kbs)/count(*) AS \"Used KBS\"\n  , sum(avail_kbs)/count(*) * -1 AS \"Avail KBs\"\nFROM\n  ${v_schema}.disk_space d\nWHERE\n  $__timeFilter(d.period)\n  GROUP BY 1\n  ORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Cumulative Cluster Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 84 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts_round(d.period, $v_interval ) AS time\n  , d.hostname||':'||s.mntpt\n  , sum(d.rkbs) as rkbs\n  , sum(d.wkbs) * -1 as wkbs\nFROM\n  ${v_schema}.disk d\n  JOIN ${v_schema}._storage s ON (d.hostname = s.hostname AND d.device = s.diskdevice)\n  JOIN public.cluster_hosts ch ON (ch.cluster_id = public.cluster_id_from_schema('$v_schema'))\n  JOIN ${v_schema}.cat_gp_segment_configuration gsc ON (ch.hostname = gsc.hostname OR ch.altname = gsc.hostname)\nWHERE\n  $__timeFilter(d.period)\n  AND s.mntpt = '/'||split_part(gsc.datadir, '/', 2)\n  GROUP BY 1, 2\n  ORDER BY 1, 2;\n"
    }
   ]
  },
  {
   "title": "Cumulative Cluster Disk Wait",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 93 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts_round(d.period, $v_interval ) AS time\n  , d.hostname||':'||s.mntpt\n  , sum(d.await) as await\nFROM\n  ${v_schema}.disk d\n  JOIN ${v_schema}._storage s ON (d.hostname = s.hostname AND d.device = s.diskdevice)\n  JOIN public.cluster_hosts ch ON (ch.cluster_id = public.cluster_id_from_schema('$v_schema'))\n  JOIN ${v_schema}.cat_gp_segment_configuration gsc ON (ch.hostname = gsc.hostname OR ch.altname = gsc.hostname)\nWHERE\n  $__timeFilter(d.period)\n  AND s.mntpt = '/'||split_part(gsc.datadir, '/', 2)\n  GROUP BY 1, 2\n  ORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Cumulative Cluster Load Average 1 & Blocked Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 102 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts_round(d.period, $v_interval ) AS time\n  -- format('%s:%s',d.hostname,s.mntpt) AS metric,\n  , sum(d.ldavg_1) as ldavg_1\n  , sum(d.blocked) * -1 AS blocked\nFROM\n  ${v_schema}.ldavg d\nWHERE\n  $__timeFilter(d.period)\n  GROUP BY 1\n  ORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Cumulative Cluster User & System CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 111 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts_round(d.period, $v_interval ) AS time\n  , sum(d.usr)/ $v_interval  as \"User %\"\n  , sum(d.sys)/ $v_interval  AS \"System %\"\nFROM\n  ${v_schema}.cpu d\nWHERE\n  $__timeFilter(d.period)\n  AND cpu = 'all'\n  GROUP BY 1\n  ORDER BY 1;\n"
    },
    {
     "rawSql": "WITH mins AS (\nSELECT min(period)\n  FROM ${v_schema}.cpu\n), stats AS (\nSELECT c1.value::int AS cores\n     , c2.value::int AS hosts\n  FROM public.cluster_attribs c1, public.cluster_attribs c2\n WHERE c1.domain = 'segment.hosts'\n   AND c2.domain = 'segment.host.cores'\n   AND c1.cluster_id = public.cluster_id_from_schema('${v_schema}')\n   AND c1.cluster_id = c2.cluster_id\n)\nSELECT ts_round(c.period, $v_interval ) AS \"time\"\n     , s.cores * 100 * s.hosts AS \"Cluster Maximum Pct\"\n  FROM ${v_schema}.cpu c, stats s\n WHERE $__timeFilter(period)\n ORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Cumulative Cluster Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 120 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts_round(d.period, $v_interval ) AS time\n  , d.hostname\n  , sum(d.memused_pct)/count(*) as \"Used %\"\nFROM\n  ${v_schema}.memory d, public.cluster_hosts h\nWHERE\n  $__timeFilter(d.period)\n  AND public.cluster_id_from_schema('${v_schema}') = cluster_id\n  AND d.hostname = h.hostname\n  AND NOT h.is_mdw\n  GROUP BY 1, 2\n  ORDER BY 1, 2;\n"
    }
   ]
  },
  {
   "title": "Cumulative Swap Util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 129 },
   "targets": [
    {
     "rawSql": "SELECT \n  ts_round(d.period, $v_interval ) AS time\n  , d.hostname\n  , sum(d.swpused_pct)/count(*) as \"Used %\"\nFROM\n  ${v_schema}.swap d, public.cluster_hosts h\nWHERE\n  $__timeFilter(d.period)\n  AND public.cluster_id_from_schema('${v_schema}') = cluster_id\n  AND d.hostname = h.hostname\n--  AND NOT h.is_mdw\n  GROUP BY 1, 2\n  ORDER BY 1, 2;\n"
    }
   ]
  },
  {
   "title": "Cumulative Network Util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 138 },
   "targets": [
    {
     "rawSql": "SELECT \n  ts_round(d.period, $v_interval ) AS time\n  , d.hostname || ' ' || d.iface\n  , sum(d.ifutil_pct)/count(*) as \"Used %\"\nFROM\n  ${v_schema}.network_dev d, public.cluster_hosts h\nWHERE\n  $__timeFilter(d.period)\n  AND public.cluster_id_from_schema('${v_schema}') = cluster_id\n  AND d.hostname = h.hostname\n  AND d.iface <> 'lo'\n--  AND NOT h.is_mdw\n  GROUP BY 1, 2\n  ORDER BY 1, 2;\n"
    }
   ]
  },
  {
   "title": "Cumulative Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 147 },
   "targets": [
    {
     "rawSql": "SELECT \n  ts_round(d.period, $v_interval ) AS time\n  , d.hostname\n  , sum(d.rxerr_psec + d.rxdrop_psec + d.rxfram_psec + d.rxfifo_psec) AS \"RX Errors\"\n  , sum(d.txerr_psec + d.txdrop_psec + d.txcarr_psec + d.txfifo_psec) AS \"TX Errors\"\n  , sum(coll_psec) AS \"Collisions\"\nFROM\n  ${v_schema}.network_errors d, public.cluster_hosts h\nWHERE\n  $__timeFilter(d.period)\n  AND public.cluster_id_from_schema('${v_schema}') = cluster_id\n  AND d.hostname = h.hostname\n  AND d.iface <> 'lo'\n--  AND NOT h.is_mdw\n  GROUP BY 1, 2\n  ORDER BY 1, 2;\n"
    }
   ]
  }
 ]
}